"""Equivalence of the C runtime (firmware/) with the Python reference.

The harness ``firmware/test/eea_harness.c`` is compiled together with a header
generated by ``tools/export_c.py`` from a ``PolicyBundle``; the same event
stream (begin_step / measurement / transmission) is fed to the Python
``NodeStateTracker`` and to the C tracker, and observations, rule-based
actions, plan_execution results and MLP actions are compared.

Skipped when no C compiler is available.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

from edgeengine_aware import EdgeEngineAwareEnv, NodeProfile, RuleBasedParams, RuleBasedPolicy, default_config
from edgeengine_aware.actions import plan_execution
from edgeengine_aware.deployment import export_policy
from edgeengine_aware.interfaces import Measurement, Packet
from edgeengine_aware.observation import NodeStateTracker, ObservationBuilder
from edgeengine_aware.rl import NumpyMLPPolicy

ROOT = Path(__file__).resolve().parents[1]
FIRMWARE = ROOT / "firmware"
sys.path.insert(0, str(ROOT / "tools"))
from export_c import export_header  # noqa: E402

CC = shutil.which("cc") or shutil.which("gcc") or shutil.which("clang")
pytestmark = pytest.mark.skipif(CC is None, reason="no C compiler available")


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def random_mlp_model(rng: np.random.Generator, n_modes: int = 3, hidden: int = 32, output: str = "multidiscrete_logits") -> dict:
    n_out = 3 + (1 + n_modes) if output == "multidiscrete_logits" else 3 * (1 + n_modes)
    dims = [18, hidden, hidden, n_out]
    acts = ["tanh", "relu", "linear"]
    layers = []
    for i in range(3):
        W = rng.normal(0, 1 / np.sqrt(dims[i]), size=(dims[i + 1], dims[i])).astype(np.float32)
        b = rng.normal(0, 0.1, size=dims[i + 1]).astype(np.float32)
        layers.append({"W": W.tolist(), "b": b.tolist(), "activation": acts[i]})
    model = {"type": "mlp", "input_dim": 18, "layers": layers, "output": output, "n_modes": n_modes}
    if output == "multidiscrete_logits":
        model["output_split"] = [3, 1 + n_modes]
    return model


class Harness:
    """Compile the C harness for a bundle and talk to it over pipes."""

    def __init__(self, bundle: dict, build_dir: Path):
        build_dir.mkdir(parents=True, exist_ok=True)
        (build_dir / "eea_policy_data.h").write_text(export_header(bundle, source="test"))
        exe = build_dir / "eea_harness"
        cmd = [CC, "-std=c99", "-O2", "-Wall", "-Wextra", "-Werror", "-I", str(FIRMWARE), "-I", str(build_dir),
               str(FIRMWARE / "eea_node.c"), str(FIRMWARE / "test" / "eea_harness.c"), "-o", str(exe), "-lm"]
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        self.proc = subprocess.Popen([str(exe)], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True, bufsize=1)

    def cmd(self, line: str) -> str:
        assert self.proc.stdin and self.proc.stdout
        self.proc.stdin.write(line + "\n")
        self.proc.stdin.flush()
        out = self.proc.stdout.readline()
        if not out:
            raise RuntimeError(f"harness died on {line!r}")
        return out.strip()

    def obs(self) -> np.ndarray:
        return np.array([float.fromhex(x) for x in self.cmd("O").split()], dtype=np.float32)

    def close(self) -> None:
        if self.proc.stdin:
            self.proc.stdin.close()
        self.proc.wait(timeout=10)


def hexfloats(values) -> str:
    return " ".join(float(v).hex() for v in np.asarray(values, dtype=np.float32).astype(float))


def random_event_stream(rng: np.random.Generator, profile: NodeProfile, n_steps: int = 300):
    """Yield (kind, payload) events resembling a real episode."""
    dt = profile.timestep_s
    now = 0.0
    events = []
    measurement = None
    for k in range(n_steps):
        tod = now % 86400.0
        cap = 300.0 if k < n_steps // 2 else 250.0
        energy = float(rng.uniform(0, cap))
        harvest = float(max(0.0, rng.normal(0.002, 0.002)))
        prio = int(rng.integers(0, 3)) if rng.random() < 0.3 else -1
        events.append(("B", (now, tod, energy, cap, harvest, prio)))
        if rng.random() < 0.6:
            level = int(rng.integers(1, 3))
            measurement = Measurement(float(rng.uniform(0, 1)), now, level, profile.sensing_noise_std[level])
            events.append(("M", measurement))
        if measurement is not None and rng.random() < 0.4:
            mode = int(rng.integers(0, profile.n_modes))
            r = rng.random()
            acked = None if r < 0.1 else bool(r < 0.7)
            margin = float(rng.normal(8, 6)) if (acked and rng.random() < 0.9) else None
            events.append(("X", (Packet(measurement, now), acked, now, mode, margin)))
        if rng.random() < 0.1:
            events.append(("Q", int(rng.integers(0, 3))))
        events.append(("O", None))
        now += dt
    return events


def drive(events, tracker: NodeStateTracker, builder: ObservationBuilder, harness: Harness, policy=None, mlp=None):
    """Replay the events on both sides; return the list of (py_obs, c_obs, py_act, c_act, py_mlp, c_mlp)."""
    rows = []
    for kind, payload in events:
        if kind == "B":
            now, tod, energy, cap, harvest, prio = payload
            tracker.begin_step(now_s=now, time_of_day_s=tod, energy_j=energy, capacity_j=cap, harvest_power_w=harvest, priority=None if prio < 0 else prio)
            assert harness.cmd(f"B {now!r} {tod!r} {energy!r} {cap!r} {harvest!r} {prio}") == "ok"
        elif kind == "M":
            m: Measurement = payload
            tracker.on_measurement(m)
            assert harness.cmd(f"M {m.value!r} {m.timestamp_s!r} {m.level} {m.noise_std!r}") == "ok"
        elif kind == "X":
            packet, acked, now, mode, margin = payload
            tracker.on_transmission(packet, acked, now, mode=mode, margin_db=margin)
            a = -1 if acked is None else int(acked)
            assert harness.cmd(f"X {packet.sent_at_s!r} {a} {now!r} {mode} {int(margin is not None)} {0.0 if margin is None else margin!r}") == "ok"
        elif kind == "Q":
            tracker.set_priority(payload)
            assert harness.cmd(f"Q {payload}") == "ok"
        elif kind == "O":
            py_obs = builder.build(tracker.state())
            c_obs = harness.obs()
            py_act = c_act = py_mlp = c_mlp = None
            if policy is not None:
                py_act = tuple(int(x) for x in policy.act(py_obs))
                c_act = tuple(int(x) for x in harness.cmd("R").split())
            if mlp is not None:
                py_mlp = (tuple(int(x) for x in mlp.act(py_obs)), mlp.forward(py_obs))
                parts = harness.cmd("N").split()
                c_mlp = ((int(parts[0]), int(parts[1])), np.array([float.fromhex(x) for x in parts[2:]], dtype=np.float32))
            rows.append((py_obs, c_obs, py_act, c_act, py_mlp, c_mlp))
    return rows


# ---------------------------------------------------------------------------
# fixtures
# ---------------------------------------------------------------------------
@pytest.fixture(scope="module")
def profile() -> NodeProfile:
    return NodeProfile.from_config(default_config())


@pytest.fixture(scope="module")
def rule_harness(profile, tmp_path_factory):
    policy = RuleBasedPolicy(RuleBasedParams(), profile)
    bundle = json.loads(export_policy(policy, profile, policy_type="rule_based").to_json())
    h = Harness(bundle, tmp_path_factory.mktemp("c_rule"))
    yield h
    h.close()


@pytest.fixture(scope="module")
def mlp_model():
    return random_mlp_model(np.random.default_rng(7))


@pytest.fixture(scope="module")
def mlp_harness(profile, mlp_model, tmp_path_factory):
    bundle = json.loads(export_policy(NumpyMLPPolicy(mlp_model), profile, policy_type="mlp", model=mlp_model).to_json())
    h = Harness(bundle, tmp_path_factory.mktemp("c_mlp"))
    yield h
    h.close()


# ---------------------------------------------------------------------------
# tests
# ---------------------------------------------------------------------------
def test_export_header_mentions_bundle(profile):
    policy = RuleBasedPolicy(RuleBasedParams(), profile)
    bundle = json.loads(export_policy(policy, profile, policy_type="rule_based", notes="unit").to_json())
    header = export_header(bundle, source="x")
    assert "EEA_HAS_RULE_PARAMS" in header and "EEA_PROFILE" in header
    assert '#define EEA_BUNDLE_NOTES "unit"' in header
    assert ".n_modes = 3," in header


def test_tracker_and_observation_match_bit_for_bit(profile, rule_harness):
    rng = np.random.default_rng(1)
    tracker = NodeStateTracker(profile)
    builder = ObservationBuilder(profile)
    assert rule_harness.cmd("Z") == "ok"
    rows = drive(random_event_stream(rng, profile, 400), tracker, builder, rule_harness)
    assert len(rows) == 400
    max_diff = 0.0
    exact = 0
    for py_obs, c_obs, *_ in rows:
        assert py_obs.dtype == np.float32 and c_obs.shape == (18,)
        diff = np.abs(py_obs.astype(np.float64) - c_obs.astype(np.float64))
        max_diff = max(max_diff, float(diff.max()))
        exact += int(np.array_equal(py_obs, c_obs))
    # sin/cos may differ by one float32 ulp between libm builds; everything else is exact
    assert max_diff <= 1.2e-7, max_diff
    assert exact >= 0.95 * len(rows)


def test_rule_based_actions_match(profile, rule_harness):
    rng = np.random.default_rng(2)
    tracker = NodeStateTracker(profile)
    builder = ObservationBuilder(profile)
    policy = RuleBasedPolicy(RuleBasedParams(), profile)
    assert rule_harness.cmd("Z") == "ok"
    rows = drive(random_event_stream(rng, profile, 600), tracker, builder, rule_harness, policy=policy)
    mismatches = [(p, c) for _, _, p, c, _, _ in rows if p != c]
    assert not mismatches, mismatches[:5]
    # the stream must exercise the rules: several distinct actions
    assert len({p for _, _, p, _, _, _ in rows}) >= 4


def test_rule_based_on_explicit_observations(profile, rule_harness):
    """Random observations (not only reachable ones) cover every branch."""
    rng = np.random.default_rng(3)
    policy = RuleBasedPolicy(RuleBasedParams(), profile)
    n_mismatch = 0
    for _ in range(2000):
        obs = rng.uniform(0, 1, 18).astype(np.float32)
        obs[11] = rng.choice([0.0, 0.5, 1.0])  # priority
        obs[6] = rng.choice([0.0, 0.2, 0.8])  # quality tag
        if rng.random() < 0.3:
            obs[14] = 1.0  # no link estimate
        if rng.random() < 0.2:
            obs[8] = 1.0  # never reported
        assert rule_harness.cmd("V " + hexfloats(obs)) == "ok"
        c_act = tuple(int(x) for x in rule_harness.cmd("R").split())
        py_act = tuple(int(x) for x in policy.act(obs))
        n_mismatch += py_act != c_act
    assert n_mismatch == 0


def test_plan_execution_matches(profile, rule_harness):
    rng = np.random.default_rng(4)
    for _ in range(500):
        sense, tx = int(rng.integers(0, 3)), int(rng.integers(0, 1 + profile.n_modes))
        cap = float(rng.choice([300.0, 120.0, 30.0]))
        stored = float(rng.uniform(0, cap))
        has_meas = bool(rng.random() < 0.5)
        plan = plan_execution(
            np.array([sense, tx]),
            stored_energy_j=stored,
            baseline_energy_j=profile.baseline_energy_j,
            reserve_energy_j=profile.reserve_soc * cap,
            sensing_energy_j=profile.sensing_energy_j,
            tx_energy_j=profile.tx_energy_j,
            has_measurement=has_meas,
        )
        parts = rule_harness.cmd(f"P {sense} {tx} {stored!r} {cap!r} {int(has_meas)}").split()
        c_level, c_tx, c_mode = int(parts[0]), bool(int(parts[1])), int(parts[2])
        c_sense_j, c_tx_j = float.fromhex(parts[3]), float.fromhex(parts[4])
        c_rej = (bool(int(parts[5])), bool(int(parts[6])), bool(int(parts[7])))
        assert (c_level, c_tx, c_mode) == (plan.sensing_level, plan.transmit, plan.mode)
        assert c_sense_j == plan.sensing_energy_j and c_tx_j == plan.tx_energy_j
        assert c_rej == ("sensing:insufficient_energy" in plan.rejected, "transmit:no_measurement" in plan.rejected, "transmit:insufficient_energy" in plan.rejected)


def test_mlp_actions_match(profile, mlp_model, mlp_harness):
    rng = np.random.default_rng(5)
    mlp = NumpyMLPPolicy(mlp_model)
    tracker = NodeStateTracker(profile)
    builder = ObservationBuilder(profile)
    assert mlp_harness.cmd("Z") == "ok"
    rows = drive(random_event_stream(rng, profile, 300), tracker, builder, mlp_harness, mlp=mlp)
    n_bad = 0
    for _, _, _, _, (py_act, py_logits), (c_act, c_logits) in rows:
        np.testing.assert_allclose(c_logits, py_logits, rtol=1e-5, atol=1e-6)
        if py_act != c_act:  # only acceptable at a numerical tie
            n1 = 3
            for seg in (py_logits[:n1], py_logits[n1:]):
                top2 = np.sort(seg)[-2:]
                assert top2[1] - top2[0] < 1e-5
            n_bad += 1
    assert n_bad <= 1
    assert len({a for _, _, _, _, (a, _), _ in rows}) >= 2


def test_mlp_flat_q_values_decoding(profile, tmp_path):
    model = random_mlp_model(np.random.default_rng(9), output="flat_q_values")
    bundle = json.loads(export_policy(NumpyMLPPolicy(model), profile, policy_type="mlp", model=model).to_json())
    h = Harness(bundle, tmp_path / "c_flat")
    try:
        mlp = NumpyMLPPolicy(model)
        rng = np.random.default_rng(10)
        for _ in range(300):
            obs = rng.uniform(0, 1, 18).astype(np.float32)
            assert h.cmd("V " + hexfloats(obs)) == "ok"
            parts = h.cmd("N").split()
            c_act = (int(parts[0]), int(parts[1]))
            py_act = tuple(int(x) for x in mlp.act(obs))
            q = mlp.forward(obs)
            if c_act != py_act:
                top2 = np.sort(q)[-2:]
                assert top2[1] - top2[0] < 1e-5
    finally:
        h.close()


def test_exported_ppo_bundle_if_present(profile, tmp_path):
    bundle_path = ROOT / "examples" / "bundles" / "ppo_default.json"
    if not bundle_path.exists():
        pytest.skip("shipped PPO bundle not found")
    bundle = json.loads(bundle_path.read_text())
    h = Harness(bundle, tmp_path / "c_ppo")
    try:
        mlp = NumpyMLPPolicy(bundle["model"])
        env = EdgeEngineAwareEnv(default_config())
        obs, _ = env.reset(seed=1234)
        n_bad = 0
        for _ in range(400):
            assert h.cmd("V " + hexfloats(obs)) == "ok"
            parts = h.cmd("N").split()
            c_act = (int(parts[0]), int(parts[1]))
            py_act = tuple(int(x) for x in mlp.act(obs))
            if c_act != py_act:
                n_bad += 1
            obs, _, term, trunc, _ = env.step(np.array(py_act))
            if term or trunc:
                break
        assert n_bad == 0
    finally:
        h.close()
